package br.com.stackedu.cdd;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import com.fasterxml.jackson.databind.ObjectMapper;

import br.com.stackedu.cdd.Configuracoes.CDDConfig.Rules;

public class Configuracoes {

    private static CDDConfig config = carregar();

    public static int limite() {
        return config.limitOfComplexity;
    }

    public static List<Rules> regras() {
        return config.rules;
    }

    private static CDDConfig carregar() {
        try {
            String config = Files.readString(Paths.get("cdd.json"));

            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(config, CDDConfig.class);

        } catch (IOException e) {
            throw new PluginCDDException("O arquivo 'cdd.json' não foi encontrado na raiz do projeto!");
        }
    }

    static class CDDConfig {
        private int limitOfComplexity;
        private boolean methodsAutoGenerated;
        private List<Rules> rules;

        public int getLimitOfComplexity() {
            return limitOfComplexity;
        }

        public void setLimitOfComplexity(int limitOfComplexity) {
            this.limitOfComplexity = limitOfComplexity;
        }

        public boolean isMethodsAutoGenerated() {
            return methodsAutoGenerated;
        }

        public void setMethodsAutoGenerated(boolean methodsAutoGenerated) {
            this.methodsAutoGenerated = methodsAutoGenerated;
        }

        public List<Rules> getRules() {
            return rules;
        }

        public void setRules(List<Rules> rules) {
            this.rules = rules;
        }

        static class Rules {
            private String name;
            private String cost;
            private List<String> parameters;

            public String getName() {
                return name;
            }

            public void setName(String name) {
                this.name = name;
            }

            public String getCost() {
                return cost;
            }

            public void setCost(String cost) {
                this.cost = cost;
            }

            public List<String> getParameters() {
                return parameters;
            }

            public void setParameters(List<String> parameters) {
                this.parameters = parameters;
            }
        }

    }
}
