package br.com.stackedu.cdd.config;

import java.util.List;

public class JSONParser {
    private int limite;
    private boolean methodsAutoGenerated;
    private List<Regras> regras;

    public JSONParser() {
    }

    public int getLimite() {
        return limite;
    }

    public boolean isMethodsAutoGenerated() {
        return methodsAutoGenerated;
    }

    public List<Regras> getRegras() {
        return regras;
    }

    public static enum RegrasDefinidas {

        IF_STATEMENT, TRY_CATCH_STATEMENT, SWITCH_STATEMENT, CONDITION, FOR_STATEMENT, FOREACH_STATEMENT,
        WHILE_STATEMENT, CONTEXT_COUPLING, METHODS_AUTOGEN, ANNOTATION, LAMBDA_EXPRESSION, METHOD, THROW_STATEMENT,
        YIELD_STATEMENT, SUPER_EXPRESSION, ANONYMOUS_CLASS, LOCAL_VARIABLE;
    }

    public static class Regras {

        private String name;
        private String cost;
        private String parameters;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getCost() {
            return cost;
        }

        public void setCost(String cost) {
            this.cost = cost;
        }

        public String getParameters() {
            return parameters;
        }

        public void setParameters(String parameters) {
            this.parameters = parameters;
        }
    }
}