package br.com.stackedu.cdd.config;

/**
 * Supported rules
 * @author gustavopinto
 *
 */
public enum RegraSuportada {

    IF_STATEMENT, TRY_CATCH_STATEMENT, SWITCH_STATEMENT, CONDITION, FOR_STATEMENT, FOREACH_STATEMENT,
    WHILE_STATEMENT, CONTEXT_COUPLING, METHODS_AUTOGEN, ANNOTATION, LAMBDA_EXPRESSION, METHOD, THROW_STATEMENT,
    YIELD_STATEMENT, SUPER_EXPRESSION, ANONYMOUS_CLASS, LOCAL_VARIABLE;
}